# Generated by Django 5.0.4 on 2024-08-20 20:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDominio', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historial_IP_FW_Bloqueadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(default='Desconocido', max_length=100)),
                ('iso2', models.CharField(default='00', max_length=2)),
                ('iso3', models.CharField(default='000', max_length=3)),
                ('phonecod', models.CharField(default='00000', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='RangoExonerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipInicio', models.CharField(max_length=15)),
                ('ipFin', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DominioPermitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.dominio')),
            ],
        ),
        migrations.CreateModel(
            name='BloqueadasTemporales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField(default=datetime.datetime(2024, 8, 20, 15, 14, 22, 753833), null=True)),
                ('fechaFin', models.DateTimeField()),
                ('ipBloqueada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='control.historial_ip_fw_bloqueadas')),
            ],
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('Bloqueado', 'Bloqueado'), ('Bloqueado Temporal', 'Bloqueado Temporal'), ('Pendiente', 'Pendiente'), ('Exonerado', 'Exonerado'), ('No Bloqueado', 'No Bloqueado'), ('Nuevo', 'Nuevo')], default='Nuevo', max_length=100)),
                ('malicioso', models.IntegerField(null=True)),
                ('isp', models.CharField(max_length=100, null=True)),
                ('tipoUso', models.CharField(max_length=100, null=True)),
                ('ataques', models.CharField(max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('peticiones', models.IntegerField(default=0, null=True)),
                ('firewall', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=5)),
                ('usuario', models.CharField(max_length=100, null=True)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2024, 8, 20, 15, 14, 22, 753833), null=True)),
                ('fuente', models.CharField(choices=[('SOC', 'SOC'), ('Fuentes de Inteligencia', 'Fuentes de Inteligencia'), ('Pentesting', 'Pentesting'), ('Ejercicios SI', 'Ejercicios SI'), ('Desconocido', 'Desconocido')], default='Desconocido', max_length=100)),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.dominio')),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='control.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Historial_IP_FW_Permitidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('ipPermitida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='control.ip')),
            ],
        ),
        migrations.AddField(
            model_name='historial_ip_fw_bloqueadas',
            name='ipBloqueada',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='control.ip'),
        ),
        migrations.CreateModel(
            name='Casos_Especiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.CharField(default='Motivo Desconocido', max_length=200)),
                ('ipEspecial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='control.ip')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('BLOQUEADO', 'Bloqueado'), ('PERMITIDO', 'Permitido')], max_length=20)),
                ('fecha', models.DateTimeField()),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.ip')),
            ],
        ),
    ]
