# Generated by Django 5.0.4 on 2025-01-07 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloqueadastemporales',
            name='fechaInicio',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 11, 7, 50, 125787), null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 11, 7, 50, 124487), null=True),
        ),
    ]
