# Generated by Django 5.0.4 on 2024-07-30 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_bloqueadastemporales_fechainicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='fuente',
            field=models.CharField(choices=[('SOC', 'SOC'), ('Fuentes de Inteligencia', 'Fuentes de Inteligencia'), ('Pentesting', 'Pentesting'), ('Ejercicios SI', 'Ejercicios SI'), ('Desconocido', 'Desconocido')], default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='bloqueadastemporales',
            name='fechaInicio',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 16, 55, 50, 845062), null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 16, 55, 50, 845062), null=True),
        ),
    ]
