# Generated by Django 5.0.4 on 2024-07-30 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_ip_fuente_alter_bloqueadastemporales_fechainicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RangoExonerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipInicio', models.CharField(max_length=15)),
                ('ipFin', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='bloqueadastemporales',
            name='fechaInicio',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 18, 51, 50, 621659), null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 18, 51, 50, 621659), null=True),
        ),
    ]
