# Generated by Django 5.0.4 on 2025-01-21 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_alter_bloqueadastemporales_fechainicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloqueadastemporales',
            name='fechaInicio',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 20, 21, 32, 18, 828141), null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 20, 21, 32, 18, 825855), null=True),
        ),
    ]
