# Generated by Django 5.0.4 on 2024-07-31 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_rangoexonerado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloqueadastemporales',
            name='fechaInicio',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 18, 58, 38, 189148), null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 18, 58, 38, 189148), null=True),
        ),
    ]
