# Generated by Django 5.0.4 on 2025-01-22 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_alter_bloqueadastemporales_fechainicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloqueadastemporales',
            name='fechaInicio',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 21, 21, 57, 23, 595077), null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 21, 21, 57, 23, 594080), null=True),
        ),
    ]
