# Generated by Django 5.0.4 on 2025-01-22 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_alter_bloqueadastemporales_fechainicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloqueadastemporales',
            name='fechaInicio',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 21, 23, 25, 19, 21688), null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 21, 23, 25, 19, 19694), null=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='iso2',
            field=models.CharField(default='00', max_length=10),
        ),
        migrations.AlterField(
            model_name='pais',
            name='iso3',
            field=models.CharField(default='000', max_length=10),
        ),
        migrations.AlterField(
            model_name='pais',
            name='name',
            field=models.CharField(default='Desconocido', max_length=500),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='phonecod',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
